#!/usr/bin/env node
// SINH TU DONG tu .claude/skills — dung sua tay file nay, sua ban goc roi chay: npm run sync:agents
/**
 * Kiem tra ky thuat mot file anh de xuat dua len website.
 *
 * Muc dich: bat cac dau hieu anh do may tao sinh, anh qua nho/qua lon, sai dinh dang,
 * hoac thieu metadata. KHONG thay the duoc viec doi chieu nguon anh va giay phep bang tay —
 * khong co cong cu nao ket luan chac chan "anh nay do AI tao". Script chi neu co.
 *
 * Cach dung:
 *   node .agents/skills/marian-audit/scripts/check-image.mjs duong/dan/anh.jpg [anh2.jpg ...]
 *
 * Ma thoat: 0 = khong thay loi chan, 1 = co loi chan (sai dinh dang, kich thuoc, dau hieu AI).
 */

import fs from 'node:fs';
import path from 'node:path';

const files = process.argv.slice(2).filter((a) => !a.startsWith('--'));
if (files.length === 0) {
  console.error('Thieu duong dan anh.');
  process.exit(1);
}

// Chuoi thuong xuat hien trong metadata cua anh tao sinh hoac anh da chinh sua nang.
const AI_MARKERS = [
  'midjourney', 'stable diffusion', 'stablediffusion', 'dall-e', 'dalle', 'openai',
  'firefly', 'adobe firefly', 'imagen', 'gemini', 'grok', 'flux.1', 'blackforestlabs',
  'leonardo.ai', 'nightcafe', 'novelai', 'ideogram', 'recraft', 'playground ai',
  'c2pa', 'contentcredentials', 'trainedalgorithmicmedia', 'compositewithtrainedalgorithmicmedia',
  'ai-generated', 'generated by ai', 'digitalsourcetype',
];

const MIN_WIDTH = 1000; // du cho anh hero tren trang chi tiet
const MAX_BYTES = 3 * 1024 * 1024; // anh nang hon nen nen lai truoc khi commit

let hardFail = 0;

let sharp = null;
try {
  ({ default: sharp } = await import('sharp'));
} catch {
  console.log('LUU Y: chua cai "sharp" (chay "npm install"). Bo qua phan doc kich thuoc/metadata anh.\n');
}

for (const f of files) {
  const p = path.resolve(f);
  console.log(`--- ${f} ---`);

  if (!fs.existsSync(p)) {
    console.log('  x file khong ton tai\n');
    hardFail++;
    continue;
  }

  const buf = fs.readFileSync(p);
  const stat = fs.statSync(p);
  const ext = path.extname(p).toLowerCase();

  console.log(`  dung luong: ${(stat.size / 1024).toFixed(0)} KB`);
  if (!['.jpg', '.jpeg', '.png'].includes(ext)) {
    console.log(`  x duoi file "${ext}" khong duoc ho tro — chi dung .jpg/.jpeg/.png trong src/assets/real_photos/`);
    hardFail++;
  }
  if (stat.size > MAX_BYTES) {
    console.log(`  ! nang hon ${(MAX_BYTES / 1024 / 1024).toFixed(1)} MB — nen lai truoc khi commit`);
  }
  if (stat.size < 40 * 1024) {
    console.log('  ! rat nhe — kiem tra xem co phai anh thumbnail cat tu trang khac khong');
  }

  // Quet metadata tho: EXIF/XMP/ICC nam trong 512 KB dau, chu thich PNG co the o cuoi.
  const head = buf.subarray(0, Math.min(buf.length, 512 * 1024)).toString('latin1').toLowerCase();
  const tail = buf.subarray(Math.max(0, buf.length - 64 * 1024)).toString('latin1').toLowerCase();
  const hay = head + tail;

  const hits = AI_MARKERS.filter((m) => hay.includes(m));
  if (hits.length) {
    console.log(`  x DAU HIEU ANH TAO SINH trong metadata: ${hits.join(', ')}`);
    console.log('    => Du an cam tuyet doi anh AI. Tu choi anh nay tru khi chung minh duoc day la duong tinh gia.');
    hardFail++;
  } else {
    console.log('  metadata: khong thay dau hieu AI (khong dam bao tuyet doi)');
  }

  if (sharp) {
    try {
      const m = await sharp(p).metadata();
      console.log(`  dinh dang: ${m.format} · ${m.width}x${m.height} · ${m.space}${m.hasAlpha ? ' · co alpha' : ''}`);
      if (m.width < MIN_WIDTH) {
        console.log(`  x chieu rong ${m.width}px < ${MIN_WIDTH}px — qua nho cho anh chinh cua trang linh dia`);
        hardFail++;
      }
      const ratio = m.width / m.height;
      if (ratio < 0.5 || ratio > 2.5) console.log(`  ! ty le ${ratio.toFixed(2)} bat thuong — kiem tra anh co bi cat xen khong`);
      if (!m.exif) {
        console.log('  ! khong co EXIF — binh thuong voi anh tai tu Wikimedia (da bi loc), nhung');
        console.log('    neu nguoi dong gop noi "toi tu chup" thi anh goc phai con EXIF may anh/dien thoai');
      } else {
        console.log('  co EXIF (doc bang exiftool neu can doi chieu ngay chup va thiet bi)');
      }
      if (m.xmp) console.log('  co XMP — doc de xem co Content Credentials/C2PA khong');
    } catch (e) {
      console.log(`  x sharp khong doc duoc file: ${e.message}`);
      hardFail++;
    }
  }

  console.log('');
}

console.log('NHAC LAI phan khong tu dong hoa duoc — phai kiem bang tay:');
console.log('  1. Trang goc cua anh (vi du trang File: tren Wikimedia Commons, bai tin giao phan, bai bao) co that va con song.');
console.log('  2. Giu nguyen URL trang goc va ghi ro nguon trong realImageCaption/caption. Giay phep cu the');
console.log('     (CC-BY-SA, CC-BY, Public Domain...) khong bat buoc — biet thi ghi them, khong biet cung khong sao.');
console.log('  3. Ten tac gia (hoac ten trang/toa soan neu khong ro tac gia ca nhan) va nam chup neu biet.');
console.log('  4. Anh dung la linh dia dang xet, khong phai linh dia khac cung ten Duc Me.');
console.log('  5. Tim anh nguoc (reverse image search) neu nghi ngo nguon goc hoac nghi anh AI.\n');

if (hardFail > 0) {
  console.log(`=> ${hardFail} loi chan. Khong dua anh nay len website.`);
  process.exit(1);
}
console.log('=> Khong co loi chan ve mat ky thuat.');
