blank_issues_enabled: false
contact_links:
  - name: Đóng góp tư liệu qua Email
    url: mailto:minh-duc.nguyen-nam@ekino.com
    about: Nếu bạn có tệp tư liệu lịch sử lớn hoặc bộ ảnh thực địa muốn gửi trực tiếp cho người quản trị.
